### ISSUE TITLE
Can't open large image

### ISSUE THREAD

**Issue by Silme2013** [Polarrco/polarr_windows_support#18]
I have an image from 12MB camera I'm trying to open.  It appears for a split second in image thumbnail area but then the app crashes.  What makes the issue way worse is that I cannot start the app - it tries to open the last image and crashes.
Is there a limitation for the image size?
How do I clear "the last project" so I can use the app?
the image in question is uploaded

![2016_0101_010156_001](https://cloud.githubusercontent.com/assets/22779506/19289366/37b0d538-8fbf-11e6-9b6d-16f396a5030a.JPG)

**Comment by kpaddie** [comment]
Hi there,

The crashing of the editor could be due to your device's incompatibility with Polarr, or due to the large file size of the photo. Try uninstalling and reinstalling the app, then editing a small file size photo. If the editor still crashes, it is due to a device incompatibility. If so, we are sorry for the inconvenience, and are happy to reimburse you if you send your original purchase receipt to support@polarr.co.

Best,

-Polarr team
